import argparse
import json
from pathlib import Path


def md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def build_notebook(input_path: Path, title: str) -> dict:
    source = f"""from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path

import h5py
import numpy as np
import matplotlib.pyplot as plt


DATA_PATH = Path({str(input_path)!r})

plt.rcParams.update(
    {{
        "figure.figsize": (10, 5.5),
        "figure.dpi": 130,
        "savefig.dpi": 180,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.facecolor": "#f8f7f4",
        "grid.alpha": 0.3,
        "font.size": 11,
    }}
)


def _decode(value):
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, np.ndarray) and value.shape == (1,):
        return _decode(value[0])
    return value


def _parse_time_axis(time_values, time_units):
    if not time_units or not str(time_units).startswith("days since "):
        return np.asarray(time_values), "time"
    base = datetime.fromisoformat(str(time_units).replace("days since ", "").strip())
    dt = np.array([base + timedelta(days=float(day)) for day in time_values], dtype=object)
    return dt, "time"


with h5py.File(DATA_PATH, "r") as ds:
    keys = list(ds.keys())
    coord_like = {{
        "point",
        "point_name",
        "time",
        "z",
        "sample_name",
        "requested_latitude",
        "requested_longitude",
        "requested_x",
        "requested_y",
        "latitude",
        "longitude",
        "x",
        "y",
    }}
    data_var_name = next(name for name in keys if name not in coord_like and ds[name].ndim >= 2)
    data = ds[data_var_name][:]
    point_names = [_decode(v) for v in ds["point_name"][:]]
    attrs = {{k: _decode(v) for k, v in ds.attrs.items()}}
    var_attrs = {{k: _decode(v) for k, v in ds[data_var_name].attrs.items()}}
    requested_latitude = ds["requested_latitude"][:]
    requested_longitude = ds["requested_longitude"][:]
    actual_latitude = ds["latitude"][:]
    actual_longitude = ds["longitude"][:]

    has_time = "time" in ds and data.ndim == 2 and ds["time"].shape[0] == data.shape[0]
    has_sample = "sample_name" in ds
    has_z = "z" in ds and ((data.ndim == 2 and ds["z"].shape[0] == data.shape[0]) or (data.ndim == 3 and ds["z"].shape[0] == data.shape[1]))

    if has_time:
        time_values = ds["time"][:]
        time_units = _decode(ds["time"].attrs.get("units"))
        time_axis, x_label = _parse_time_axis(time_values, time_units)
    else:
        time_axis = None
        x_label = None

    if has_sample:
        sample_names = [_decode(v) for v in ds["sample_name"][:]]
    else:
        sample_names = None

    if has_z:
        z = ds["z"][:]
        z_attrs = {{k: _decode(v) for k, v in ds["z"].attrs.items()}}
    else:
        z = None
        z_attrs = {{}}

print("data variable:", data_var_name)
print("shape:", data.shape)
print("points:", point_names)
print("global attrs subset_source_files:", attrs.get("subset_source_files"))
print("var attrs:", var_attrs)
if has_time:
    print("time span:", time_axis[0], "to", time_axis[-1])
if has_sample:
    print("sample labels:", sample_names)
if has_z:
    print("z range:", float(np.min(z)), "to", float(np.max(z)))
"""
    cells = [
        md_cell(f"# {title}\n\nAutogenerated inspection notebook for `{input_path}`.\n"),
        code_cell(source),
        code_cell(
            """print("Coordinate check:")
for i, name in enumerate(point_names):
    print(f"\\n{name}")
    print(f"  requested lat/lon: {requested_latitude[i]:.6f}, {requested_longitude[i]:.6f}")
    print(f"  matched   lat/lon: {actual_latitude[i]:.6f}, {actual_longitude[i]:.6f}")
"""
        ),
        code_cell(
            """if has_time:
    fig, ax = plt.subplots(figsize=(12, 6))
    for i, name in enumerate(point_names):
        ax.plot(time_axis, data[:, i], linewidth=1.6, label=name)
    ax.set_title(f"{data_var_name} point time series")
    ax.set_xlabel(x_label)
    ax.set_ylabel(var_attrs.get("units", data_var_name))
    ax.grid(True, axis="y")
    ax.legend(frameon=False, ncol=2)
    fig.autofmt_xdate()
    plt.show()
else:
    print("Time-series plot skipped: no time axis detected.")
"""
        ),
        code_cell(
            """if has_sample and has_z and data.ndim == 3:
    for point_index, point_name in enumerate(point_names):
        fig, ax = plt.subplots(figsize=(8, 6))
        for sample_index, sample_name in enumerate(sample_names):
            ax.plot(data[sample_index, :, point_index], z, linewidth=1.8, label=sample_name)
        ax.set_title(f"{data_var_name} depth profile at {point_name}")
        ax.set_xlabel(var_attrs.get("units", data_var_name))
        ax.set_ylabel("depth (m, negative downward)")
        ax.grid(True)
        ax.legend(frameon=False)
        plt.show()
elif has_sample and data.ndim == 2:
    fig, ax = plt.subplots(figsize=(12, 5))
    for point_index, point_name in enumerate(point_names):
        ax.plot(sample_names, data[:, point_index], marker="o", linewidth=1.8, label=point_name)
    ax.set_title(f"{data_var_name} by sample")
    ax.set_xlabel("sample")
    ax.set_ylabel(var_attrs.get("units", data_var_name))
    ax.grid(True, axis="y")
    ax.legend(frameon=False, ncol=2)
    ax.tick_params(axis="x", rotation=25)
    plt.show()
else:
    print("Sample/profile plot skipped: incompatible dimensions.")
"""
        ),
        code_cell(
            """summary = {
    "data_var_name": data_var_name,
    "shape": list(data.shape),
    "point_names": point_names,
    "min": float(np.nanmin(data)),
    "max": float(np.nanmax(data)),
    "mean_by_point": {name: float(np.nanmean(data[..., i])) for i, name in enumerate(point_names)},
}
summary
"""
        ),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a generic notebook for a point-subset NetCDF output.")
    parser.add_argument("input_path", type=Path)
    parser.add_argument("output_path", type=Path)
    parser.add_argument("--title", default="Subset Check")
    args = parser.parse_args()

    notebook = build_notebook(args.input_path, args.title)
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    args.output_path.write_text(json.dumps(notebook, indent=2) + "\n")
    print(f"Wrote {args.output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
